### ISSUE TITLE
大家都是从邮件过来的吗

### ISSUE THREAD

**Issue by sanbei101** [GenTang/regression2chatgpt#1]
**好神奇的推销方式**

**Comment by GenTang** [comment]
看了一下数据，应该有一部分是的。

如果由于群发邮件打扰到您或者其他人，还请原谅。

**Comment by zly2006** [comment]
> 看了一下数据，应该有一部分是的。
> 
> 如果由于群发邮件打扰到您或者其他人，还请原谅。

原谅你妈逼，草泥马老子就没打开过你这个脑瘫repo还把骗钱邮件发我这里来了？想赚钱可以帮你妈多介绍点客人
