### ISSUE TITLE
本地下载数据集代码修改，从b站第11集开始

### ISSUE THREAD

**Issue by xufengnian-bei** [GenTang/regression2chatgpt#2]
视频中老师使用Colab进行演示，下面是手动下载数据集教程（因为直接load_data网络配置一直出问题）

1.  访问 Hugging Face 数据集页面: https://huggingface.co/datasets/code_search_net
2.  在页面上找到 "Files and versions" 部分。
3. 点击data文件夹，下载对应的python.zip

修改对应下载文件代码：

datasets = load_dataset('json', data_files='data/python/python/final/jsonl/train/*.jsonl.gz')  # 更换为自己的目录
datasets = datasets['train'].filter(lambda x: 'apache/spark' in x['repo'])                                     # 这里repository_name 更换为 repo

print(datasets[8]['original_string'])   # whole_func_string 更换为 original_string

**Comment by GenTang** [comment]
对的，非常感谢。我会在相应的代码上加上注释的。

我看了一下，是因为code-search-net在做了一层封装。具体的代码如下：
https://huggingface.co/datasets/code-search-net/code_search_net/blob/main/code_search_net.py#L197-L219

**Comment by GenTang** [comment]
@xufengnian-bei 多谢你的反馈，已增加说明
