### ISSUE TITLE
def test_lstm(): 函数问题

### ISSUE THREAD

**Issue by xufengnian-bei** [GenTang/regression2chatgpt#3]
多次运行进行排除当 B = 1时候, 实例代码会报错
def test_lstm():
    '''
    测试LSTM实现的准确性
    '''
    # 随机生成模型结构
    B, T, input_size, hidden_size, num_layers = torch.randint(1, 20, (5,)).tolist()   # 就是这一行

**Comment by GenTang** [comment]
有个小错误，现已修正，多谢
